<a href="https://colab.research.google.com/github/Swathi-Guptha/fmml2021/blob/main/10_Problem_Solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Madagascar problem

In [2]:
import numpy as np

In [3]:
A = np.array([[20, 122, 20], [35,180, 35],[50, 220, 65], [70, 300, 30]])
x = np.array([[0.05], [0.002], [0.02]])

In [4]:
# 4x3 . 3x1 = 4x1

In [5]:
y = np.matmul(A,x) - 4.0

In [6]:
y

array([[-2.356],
       [-1.19 ],
       [ 0.24 ],
       [ 0.7  ]])

In [7]:
Z = np.hstack((A,y))

In [8]:
Z

array([[ 2.000e+01,  1.220e+02,  2.000e+01, -2.356e+00],
       [ 3.500e+01,  1.800e+02,  3.500e+01, -1.190e+00],
       [ 5.000e+01,  2.200e+02,  6.500e+01,  2.400e-01],
       [ 7.000e+01,  3.000e+02,  3.000e+01,  7.000e-01]])

In [9]:
def RankArray(A,x):
  y = np.dot(A,x) - 4.0
  L = np.hstack((A,y))
  return L

In [10]:
print (RankArray(A,x))

[[ 2.000e+01  1.220e+02  2.000e+01 -2.356e+00]
 [ 3.500e+01  1.800e+02  3.500e+01 -1.190e+00]
 [ 5.000e+01  2.200e+02  6.500e+01  2.400e-01]
 [ 7.000e+01  3.000e+02  3.000e+01  7.000e-01]]


In [11]:
result = RankArray(A,x)[:,3:] > 0

In [12]:
result

array([[False],
       [False],
       [ True],
       [ True]])

In [15]:
for i in range(len(result)):
  if result[i]:
    print("Person {} is at risk".format(i+1))
  else:
    print("Person {} is not at risk".format(i+1))

Person 1 is not at risk
Person 2 is not at risk
Person 3 is at risk
Person 4 is at risk
